-- MySQL Script generated by MySQL Workbench
-- Fri Apr  6 22:32:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydontlist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydontlist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydontlist` DEFAULT CHARACTER SET utf8 ;
USE `mydontlist` ;

-- -----------------------------------------------------
-- Table `mydontlist`.`mylist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydontlist`.`mylist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(250) NULL,
  `title` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydontlist`.`mylistdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydontlist`.`mylistdetail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(250) NULL,
  `date_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) NULL,
  `mylist_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_mylistdetail_mylist_idx` (`mylist_id` ASC),
  CONSTRAINT `fk_mylistdetail_mylist`
    FOREIGN KEY (`mylist_id`)
    REFERENCES `mydontlist`.`mylist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
